In [127]:
from sklearn import datasets

### Iris Dataset
This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray

The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.

In [128]:
iris = datasets.load_iris()

In [129]:
X_iris = iris.data
y_iris = iris.target

In [130]:
X_iris

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [131]:
y_iris

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [132]:
len(y_iris)

150

In [133]:
len(X_iris)

150

### scikit learn API is consistent for Model Training for Many Estimators 
1. choose model class
2. instantiate model
3. fit (train) model on training data
4. predict (evaluate) on new data

### Model 1: KNN Classifier
Why omitted word "training"?

In [152]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [153]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)

In [154]:
model.fit(X, y)
y_model = model.predict(X)

### Measure 1: Accuracy
accuracy_score (the fraction of predicted labels that match their true value)

In [155]:
from sklearn.metrics import accuracy_score
accuracy_score(y, y_model)

1.0

#### Why did we get 100 % accuracy?

### Model Training 2: Gaussian Naive Bayes 
More: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

#### Splitting Training and Test Sets

In [138]:
from sklearn.model_selection import train_test_split
# NOT IN HERE ANY MORE: from sklearn.cross_validation import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X_iris, y_iris,
                                                random_state=1, test_size=0.5)

In [156]:
from sklearn.naive_bayes import GaussianNB # 1. choose model class
model = GaussianNB()                       # 2. instantiate model
model.fit(Xtrain, ytrain)                  # 3. fit model to data
y_model = model.predict(Xtest)             # 4. predict on new data

In [140]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_model)

0.95999999999999996

In [141]:
# K-fold Cross Validation

In [157]:
# NOT from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(model, X, y, cv=10 )

array([ 0.93333333,  0.93333333,  1.        ,  0.93333333,  0.93333333,
        0.93333333,  0.86666667,  1.        ,  1.        ,  1.        ])

### Leave One Out
Not usable for large data sets!   
sklearn.model_selection import LeaveOneOut    
not from sklearn.cross_validation import LeaveOneOut 

### ROC Curve
ex: https://en.wikipedia.org/wiki/Receiver_operating_characteristic#/media/File:Roccurves.png

### Warning about Accuracy
Precision and Recall for skewed data.
https://en.wikipedia.org/wiki/Precision_and_recall

### Confusion Matrix:
https://en.wikipedia.org/wiki/Confusion_matrix    

### Hyperparameter Optimization
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html


### Example on RandomForestClassifier
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [164]:
from sklearn.model_selection import GridSearchCV
# NOT from sklearn.grid_search import GridSearchCV

from sklearn.ensemble import RandomForestClassifier

param_grid = {'max_depth': [1, 2, 3, 4],
              'min_samples_leaf': [1, 2, 3, 4],
              'n_estimators': np.arange(5,15)}

grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=7)
# = SVC(gamma='auto')

In [165]:
grid

GridSearchCV(cv=7, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'max_depth': [1, 2, 3, 4], 'min_samples_leaf': [1, 2, 3, 4], 'n_estimators': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [166]:
grid.fit(X, y);

/opt/conda/lib/python3.6/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [167]:
grid.best_params_

{'max_depth': 2, 'min_samples_leaf': 3, 'n_estimators': 6}

In [162]:
import numpy as np
myrange = np.arange(5,15)

In [163]:
myrange

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [168]:
model = grid.best_estimator_

In [151]:
model

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=3, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=3, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)