In [1]:
from sklearn import datasets

### Iris Dataset
This data sets consists of 3 different types of irises’ (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray

The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.

In [2]:
iris = datasets.load_iris()

In [3]:
X_iris = iris.data
y_iris = iris.target

In [4]:
X_iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y_iris

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
len(y_iris)

150

In [7]:
len(X_iris)

150

### scikit learn API is consistent for Model Training for Many Estimators 
1. choose model class
2. instantiate model
3. fit (train) model on training data
4. predict (evaluate) on new data

### Model 1: KNN Classifier
Not really "training" for this model!   
fit() loads all data to memory.

In [18]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

In [19]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)

In [20]:
model.fit(X, y)
y_model = model.predict(X)

### Measure 1: Accuracy
accuracy_score (the fraction of predicted labels that match their true value)

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y, y_model)

1.0

#### When you see 100%, be suspicious!    
Why did we get 100 % accuracy?
Anything wrong?

#### TASK 1: fix it by using train_test_split function   
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

### Model Training 2: Gaussian Naive Bayes 
More: https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html

#### Splitting Training and Test Sets

In [12]:
from sklearn.model_selection import train_test_split
# NOT IN HERE ANY MORE: from sklearn.cross_validation import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X_iris, y_iris,
                                                random_state=1, test_size=0.5)

In [13]:
from sklearn.naive_bayes import GaussianNB # 1. choose model class
model = GaussianNB()                       # 2. instantiate model
model.fit(Xtrain, ytrain)                  # 3. fit model to data
y_model = model.predict(Xtest)             # 4. predict on new data

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_model)

0.96

In [15]:
# K-fold Cross Validation

In [16]:
# NOT from sklearn.cross_validation import cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(model, X, y, cv=10 )

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

### Leave One Out
Not usable for large data sets!   
sklearn.model_selection import LeaveOneOut    
not from sklearn.cross_validation import LeaveOneOut 

### ROC Curve
ex: https://en.wikipedia.org/wiki/Receiver_operating_characteristic#/media/File:Roccurves.png

### Warning about Accuracy
Precision and Recall for skewed data.
https://en.wikipedia.org/wiki/Precision_and_recall

### Confusion Matrix:
https://en.wikipedia.org/wiki/Confusion_matrix    

### Hyperparameter Optimization
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html


### Example on RandomForestClassifier
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [17]:
from sklearn.model_selection import GridSearchCV
# NOT from sklearn.grid_search import GridSearchCV

from sklearn.ensemble import RandomForestClassifier

param_grid = {'max_depth': [1, 2, 3, 4],
              'min_samples_leaf': [1, 2, 3, 4],
              'n_estimators': np.arange(5,15)}

grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=7)
# = SVC(gamma='auto')

NameError: name 'np' is not defined

In [ ]:
grid

In [ ]:
grid.fit(X, y);

In [ ]:
grid.best_params_

In [ ]:
import numpy as np
myrange = np.arange(5,15)

In [ ]:
myrange

In [ ]:
model = grid.best_estimator_

In [ ]:
model